### ISSUE TITLE
Make comments form field resizable

### ISSUE THREAD

**Issue by cmeury** [mehmetbajin/gt-course-surveys#9] opened 2015-12-11 12:06 UTC
_Observation_
- On the `write-review` page, the comments input field is not resizable.

_Expectation_
- To enter longer texts it's usually convenient to have it resizable.

**Comment by mehmetbajin** [comment] 2015-12-11 14:45
The idea was to disallow resizing to discourage lengthy reviews.

I am going to close this as a duplicate of #10 since the two are so intimately related.

**Closed as completed by mehmetbajin** 2015-12-11 14:45 UTC
