### ISSUE TITLE
Weight or filter averages by age of review

### ISSUE THREAD

**Issue by glemmon** [mehmetbajin/gt-course-surveys#36] opened 2017-01-05 14:28 UTC
I love the Average Work, Difficulty, and Rating metrics. However they can be VERY skewed because some courses have changed significantly. For instance, look at reviews for CS 6250 (Computer Networks). Many reviewers warn the reader to not be fooled by the averages, this course is much more difficult than in previous semesters.

I'd like to be able to filter or weight reviews by age. A slider along the top of the reviews page with stops at each semester would be great.

Thanks!

**Comment by mehmetbajin** [comment] 2017-02-18 21:34
+1

Duplicate of #23

**Closed as completed by mehmetbajin** 2017-02-18 21:34 UTC
